server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net/heroku_1c29a8691d4bdee
    username: b583e8ebd07f1a
    password: 6f1f0d01

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect

